spring.datasource.url=jdbc:postgresql://dpg-d8n6hskm0tmc73dpkkg0-a:5432/wealth_tracker_database
spring.datasource.username=wealth_tracker_database_user
spring.datasource.password=3PoBzHhQ2vt1UmlKF98n1oRjtYOEsHRP
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update